### ISSUE TITLE
[Question] Color input as long

### ISSUE THREAD

**Issue by AllanWang** [zsmb13/MaterialDrawerKt#48]
Is there a reason why some of the color arguments are held as a Long rather than an Int? Is it mainly to distinguish it from res attributes? Because in the end, colors are indeed ints, and right now I'm converting them with `toLong()` only to have them converted back

**Comment by zsmb13** [comment]
They take `Long` values to support directly assigning hex colors to them, like so:

    textColor = 0xFF00FF00

Since `Int.MAX_VALUE` is only `7FFFFFFF` (`2 147 483 647`), assignments of color values that are greater than that wouldn't be possible if the properties were of type `Int`, because the Kotlin compiler won't allow it. 

Oddly enough, you can make these assignments in Java, and you'll just get an overflow there. For example:

    int x = 0x80000000;
    System.out.println(x);   // -2147483648 (Integer.MIN_VALUE)

But even there, it only works for hex numbers:

    int y = 2147483648;      // Error: integer number too large

Anyhow, where are you getting color values from that you have to convert?

**Comment by AllanWang** [comment]
I see. Anything from the color class is an int (eg Color.Transparent). I take my colors from my sharedpreferences which I've set to int by default, so I didn't notice other cases.
